### ISSUE TITLE
ubuntu 16.04 间歇性自动退出

### ISSUE THREAD

**Issue by gs201510** [Ericwyn/electron-lark#19]
查看下kern.log

**Comment by lonisletend** [comment]
Fedora 31 相同问题 启动后一段时间自动退出
版本 electron-lark-1.1.1.AppImage
```log
electron-lark[24083]: segfault at 17e400751000 ip 00007f9164d229d5 sp 00007fff35d76980 error 4 in libappindicator3.so.1.0.0[7f9164d1e000+6000]
```

终端启动日志
```log
[yangxj@YXJLinux ~]$ opt/electron-lark-1.1.1.AppImage 
load config error, may be have no config file~
{}
load main page: https://feishu.cn/messenger/
(node:25697) UnhandledPromiseRejectionWarning: Error: An object could not be cloned.
    at EventEmitter.i.send (electron/js2c/renderer_init.js:105:312)
    at EventEmitter.<anonymous> (electron/js2c/renderer_init.js:101:357)
(Use `electron-lark --trace-warnings ...` to show where the warning was created)
(node:25697) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:25697) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
open url https://www.processon.com/diagraming/2c92ce091e9755fa11a07915
open url https://www.processon.com/diagraming/8145415fa14ac7be401f18d1
收到消息
{"title":"XXX","opt":{"title":"XXX","body":"XXX","key":"Message_12324356","channelId":"2343565456","channelType":1,"extra":{"imageUrls":[],"chatId":"42355446","chatType":2,"chatMode":1,"isCrypto":false,"newMessageCount":1,"avatarKey":"12d6537b-b6c9-2bc4-89a5-429527664edg","channel":{"id":"354654665","type":1},"fromChatterId":"6576876"},"messageId":"8787345","position":891,"icon":"https://s3-fs.pstatp.com/static-resource/v1/12d6537b-b6c9-2bc4-89a5-429527664edg~?image_size=72x72&amp;cut_type=&amp;quality=_q70&amp;format=image&amp;sticker_format=.webp","type":1}}
收到消息
{"title":"XXX","opt":{"title":"XXX","body":"XXX","key":"Message_12324356","channelId":"2343565456","channelType":1,"extra":{"imageUrls":[],"chatId":"42355446","chatType":2,"chatMode":1,"isCrypto":false,"newMessageCount":1,"avatarKey":"12d6537b-b6c9-2bc4-89a5-429527664edg","channel":{"id":"354654665","type":1},"fromChatterId":"6576876"},"messageId":"8787345","position":891,"icon":"https://s3-fs.pstatp.com/static-resource/v1/12d6537b-b6c9-2bc4-89a5-429527664edg~?image_size=72x72&amp;cut_type=&amp;quality=_q70&amp;format=image&amp;sticker_format=.webp","type":1}}
收到消息
{"title":"XXX","opt":{"title":"XXX","body":"XXX","key":"Message_12324356","channelId":"2343565456","channelType":1,"extra":{"imageUrls":[],"chatId":"42355446","chatType":2,"chatMode":1,"isCrypto":false,"newMessageCount":1,"avatarKey":"12d6537b-b6c9-2bc4-89a5-429527664edg","channel":{"id":"354654665","type":1},"fromChatterId":"6576876"},"messageId":"8787345","position":891,"icon":"https://s3-fs.pstatp.com/static-resource/v1/12d6537b-b6c9-2bc4-89a5-429527664edg~?image_size=72x72&amp;cut_type=&amp;quality=_q70&amp;format=image&amp;sticker_format=.webp","type":1}}
段错误 (核心已转储)

```
消息内容手动打码了
